# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "vault.leader.lab.io" do |vault_leader|
    vault_leader.vm.box="generic/centos8"
    vault_leader.vm.hostname = "vault.leader.lab.io"
    vault_leader.vm.network "public_network", ip: "192.168.0.106", bridge: "Intel(R) I211 Gigabit Network Connection"
    vault_leader.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    vault_leader.vm.network "forwarded_port", guest: 443, host: 1443, auto_correct: true
    vault_leader.vm.synced_folder "vagrant", "/vagrant"
    vault_leader.vm.provision "shell", path: "vault_leader.sh"
  end

  config.vm.define "vault.follower1.lab.io" do |vault_follower1|
    vault_follower1.vm.box="generic/centos8"
    vault_follower1.vm.hostname = "vault.follower1.lab.io"
    vault_follower1.vm.network "public_network", ip: "192.168.0.107", bridge: "Intel(R) I211 Gigabit Network Connection"
    vault_follower1.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: true
    vault_follower1.vm.network "forwarded_port", guest: 443, host: 1444, auto_correct: true
    vault_follower1.vm.synced_folder "vagrant", "/vagrant"
    vault_follower1.vm.provision "shell", path: "vault_follower_1.sh"
  end

  config.vm.define "vault.follower2.lab.io" do |vault_follower2|
    vault_follower2.vm.box="generic/centos8"
    vault_follower2.vm.hostname = "vault.follower2.lab.io"
    vault_follower2.vm.network "public_network", ip: "192.168.0.108", bridge: "Intel(R) I211 Gigabit Network Connection"
    vault_follower2.vm.network "forwarded_port", guest: 80, host: 8082, auto_correct: true
    vault_follower2.vm.network "forwarded_port", guest: 443, host: 1445, auto_correct: true
    vault_follower2.vm.synced_folder "vagrant", "/vagrant"
    vault_follower2.vm.provision "shell", path: "vault_follower_2.sh"
  end

end
 
