# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
  
    # Define the VM name box image
    box_image = "bento/ubuntu-22.04"
    #box_image = "bento/ubuntu-20.04"

    (1..3).each do |i|
      config.vm.define "ansible.node#{i}.lab.io" do |node|
        node.vm.box = box_image
        node.vm.hostname = "ansible.node#{i}.lab.io"
        config.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--cpus", "2"]
          vb.customize ["modifyvm", :id, "--memory", "4096"]
        end
        node.vm.network "public_network", ip: "192.168.0.#{110+i}", bridge: "Intel(R) I211 Gigabit Network Connection"
        node.vm.network "forwarded_port", guest: 80, host: 8080 + i, auto_correct: true
        node.vm.network "forwarded_port", guest: 443, host: 1443 + i, auto_correct: true
        node.vm.synced_folder "vagrant-shared", "/vagrant-shared"
  
        node.vm.provision "shell", inline: <<-SHELL
        echo 'ansible.node#{i}.lab.io' | sudo tee /etc/hostname && sudo hostnamectl set-hostname 'ansible.node#{i}.lab.io'
        sudo apt-get update && sudo apt-get install -y python3 software-properties-common apt-transport-https ca-certificates curl gnupg lsb-release
      
        # Add all hosts to /etc/hosts
        echo "192.168.0.111 ansible.node1.lab.io" | sudo tee -a /etc/hosts
        echo "192.168.0.112 ansible.node2.lab.io" | sudo tee -a /etc/hosts
        echo "192.168.0.113 ansible.node3.lab.io" | sudo tee -a /etc/hosts
      
        if [ #{i} -eq 1 ]; then
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
          ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y
          cat ~/.ssh/id_rsa.pub >> /vagrant-shared/id_rsa.pub
          echo -e "[managed-nodes]\nansible.node[2:3].lab.io" >> /etc/ansible/hosts
        fi
      SHELL      
  
        if i > 1
          #config.vm.provision "file", source: "/vagrant-shared/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
          node.vm.provision "shell", inline: <<-SHELL
            cat /vagrant-shared/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
            chmod 600 /home/vagrant/.ssh/authorized_keys
          SHELL
        end
      end
    end